"""Abstract strategy interface that all trading models must implement.

Every model in the arena implements on_bar() and exposes its tunable parameters
as a dictionary. This uniform interface enables the evolutionary loop to merge,
mutate, and spawn strategies without knowing their internals.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional

import pandas as pd


@dataclass
class BarData:
    """A single completed OHLCV bar. Strategies never see in-progress bars."""

    symbol: str
    timestamp: pd.Timestamp
    open: float
    high: float
    low: float
    close: float
    volume: int


@dataclass
class TradeSignal:
    """A signal generated by a strategy indicating desired action."""

    symbol: str
    side: str  # "buy" or "sell"
    quantity: int
    order_type: str = "market"  # "market" or "limit"
    limit_price: Optional[float] = None


class Strategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement:
    - on_bar(): Process a completed bar and optionally return a trade signal
    - get_params(): Return current tunable parameters as a dict
    - set_params(): Apply a parameter dictionary (used by crossover/mutation)
    - strategy_type: Class attribute identifying the strategy family
    """

    strategy_type: str = "base"

    def __init__(self, name: str, params: Optional[dict] = None):
        self.name = name
        self._bar_history: dict[str, list[BarData]] = {}
        if params:
            self.set_params(params)

    @abstractmethod
    def on_bar(self, bar: BarData) -> Optional[TradeSignal]:
        """Process a completed bar and optionally return a trade signal.

        This is the only entry point for market data. The bar is guaranteed
        to be complete (no in-progress data). The strategy should maintain
        whatever internal state it needs (indicators, lookback windows, etc.)
        and return a TradeSignal if it wants to act, or None to do nothing.
        """
        ...

    @abstractmethod
    def get_params(self) -> dict:
        """Return current tunable parameters as a flat dictionary.

        Keys should be descriptive (e.g., 'fast_period', 'rsi_threshold').
        Values should be numeric for crossover compatibility.
        """
        ...

    @abstractmethod
    def set_params(self, params: dict) -> None:
        """Apply a parameter dictionary to this strategy.

        Used by the evolutionary engine during crossover and mutation.
        Should validate and clamp values to acceptable ranges.
        """
        ...

    def record_bar(self, bar: BarData) -> None:
        """Store a bar in the history buffer for indicator computation."""
        if bar.symbol not in self._bar_history:
            self._bar_history[bar.symbol] = []
        self._bar_history[bar.symbol].append(bar)

    def get_history(self, symbol: str, lookback: int = 0) -> list[BarData]:
        """Get bar history for a symbol. If lookback=0, return all."""
        history = self._bar_history.get(symbol, [])
        if lookback > 0:
            return history[-lookback:]
        return history

    def get_close_series(self, symbol: str, lookback: int = 0) -> pd.Series:
        """Get a pandas Series of close prices for indicator computation."""
        bars = self.get_history(symbol, lookback)
        if not bars:
            return pd.Series(dtype=float)
        return pd.Series(
            [b.close for b in bars],
            index=[b.timestamp for b in bars],
            dtype=float,
        )

    def reset(self) -> None:
        """Clear internal state for a new session."""
        self._bar_history.clear()

    @classmethod
    def create(cls, name: str, params: Optional[dict] = None) -> "Strategy":
        """Factory method to create an instance with given params."""
        return cls(name=name, params=params)
