"""Abstract strategy interface that all trading models must implement.

Every model in the arena implements on_bar() and exposes its tunable parameters
as a dictionary. This uniform interface enables the evolutionary loop to merge,
mutate, and spawn strategies without knowing their internals.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Optional

import logging
import pandas as pd

from src.core.watch_rules import (
    build_watch_context,
    evaluate_entry_condition,
    evaluate_watch_condition,
)

logger = logging.getLogger(__name__)


@dataclass
class BarData:
    """A single completed OHLCV bar. Strategies never see in-progress bars."""

    symbol: str
    timestamp: pd.Timestamp
    open: float
    high: float
    low: float
    close: float
    volume: int
    minutes_remaining: Optional[float] = None  # time left in session
    news_sentiment: Optional[float] = None  # -1.0 to +1.0, None if unavailable
    regime: Optional[Any] = None  # RegimeState, set by arena before fan-out
    synthetic: bool = False  # True for bars aggregated from quote stream


@dataclass
class WatchSignal:
    """Signal indicating a strategy wants quote-level monitoring for a symbol.

    Returned by get_watch_signals() when a setup is forming but not yet
    ready for entry. The arena subscribes to quotes for the symbol, and
    the strategy receives on_watch_quote() calls until entry or TTL expiry.
    """

    symbol: str
    reason: str  # human-readable description, e.g. "near breakout threshold"
    ttl_bars: int = 5  # watch expires after this many bars without conversion
    context: dict[str, Any] = field(default_factory=dict)  # strategy-specific data


@dataclass
class TradeSignal:
    """A signal generated by a strategy indicating desired action."""

    symbol: str
    side: str  # "buy" or "sell"
    quantity: float
    order_type: str = "market"  # "market" or "limit"
    limit_price: Optional[float] = None
    stop_loss_pct: Optional[float] = None  # e.g., 2.0 = 2% stop-loss
    take_profit_pct: Optional[float] = None  # e.g., 3.0 = 3% take-profit


class Strategy(ABC):
    """Abstract base class for all trading strategies.

    Subclasses must implement:
    - on_bar(): Process a completed bar and optionally return a trade signal
    - get_params(): Return current tunable parameters as a dict
    - set_params(): Apply a parameter dictionary (used by crossover/mutation)
    - strategy_type: Class attribute identifying the strategy family
    """

    strategy_type: str = "base"

    # Stop opening new positions when this many minutes remain
    NO_BUY_WINDOW: float = 10.0
    # Force-sell all positions when this many minutes remain
    LIQUIDATION_WINDOW: float = 3.0

    def __init__(self, name: str, params: Optional[dict] = None):
        self.name = name
        self.current_capital: float = 2_000.0
        self.initial_capital: float = 2_000.0
        self._bar_history: dict[str, list[BarData]] = {}
        self._positions: dict[str, float] = {}  # symbol -> quantity (set by arena)
        self._entry_prices: dict[str, float] = {}  # symbol -> avg entry price (set by arena)
        # Risk management defaults — 2% stop-loss, 3% take-profit.
        # Strategies can override in their own __init__/set_params.
        self.stop_loss_pct: Optional[float] = 2.0
        self.take_profit_pct: Optional[float] = 3.0
        # LLM-generated watch rules (list of rule dicts)
        self._watch_rules: list[dict] = []
        # Cached indicator values per symbol, updated each on_bar()
        self._indicators: dict[str, dict[str, float]] = {}
        if params:
            self.set_params(params)
            # Load watch rules from params (set by LLM, not by set_params)
            self._watch_rules = params.get("_watch_rules", [])

    def compute_quantity(self, price: float, allocation_pct: float = 0.25) -> float:
        """Compute fractional shares to buy given price and desired capital allocation.

        Alpaca paper trading supports fractional shares for market orders.
        Returns at least 0.01 shares or $1 notional (whichever is larger),
        rounded to 4 decimal places.
        """
        if price <= 0 or self.current_capital <= 0:
            return 0.0
        dollar_amount = self.current_capital * allocation_pct
        shares = dollar_amount / price
        # Minimum: max of 0.01 shares or $1 notional
        min_shares = max(0.01, 1.0 / price)
        if shares < min_shares:
            # Can we afford the minimum?
            if self.current_capital >= min_shares * price:
                return round(min_shares, 4)
            return 0.0
        return round(shares, 4)

    @abstractmethod
    def on_bar(self, bar: BarData) -> Optional[TradeSignal]:
        """Process a completed bar and optionally return a trade signal.

        This is the only entry point for market data. The bar is guaranteed
        to be complete (no in-progress data). The strategy should maintain
        whatever internal state it needs (indicators, lookback windows, etc.)
        and return a TradeSignal if it wants to act, or None to do nothing.
        """
        ...

    @abstractmethod
    def get_params(self) -> dict:
        """Return current tunable parameters as a flat dictionary.

        Keys should be descriptive (e.g., 'fast_period', 'rsi_threshold').
        Values should be numeric for crossover compatibility.
        """
        ...

    @abstractmethod
    def set_params(self, params: dict) -> None:
        """Apply a parameter dictionary to this strategy.

        Used by the evolutionary engine during crossover and mutation.
        Should validate and clamp values to acceptable ranges.
        """
        ...

    def get_indicators(self, symbol: str) -> dict[str, float]:
        """Return current indicator values for the given symbol.

        Subclasses override to expose strategy-specific indicators. Values
        are cached during on_bar() and read by the generic watch evaluator.
        Base implementation provides close and has_position.
        """
        indicators = self._indicators.get(symbol, {})
        # Always include base indicators
        history = self._bar_history.get(symbol, [])
        if history:
            indicators.setdefault("close", history[-1].close)
        indicators["has_position"] = 1.0 if self._positions.get(symbol, 0) > 0 else 0.0
        return indicators

    def get_watch_signals(self, bar: BarData) -> list[WatchSignal]:
        """Evaluate LLM-generated watch rules against current indicators.

        Each rule's watch_when condition is checked. If met and no position
        held, a WatchSignal is created with frozen context values.
        """
        if not self._watch_rules:
            return []
        if self._positions.get(bar.symbol, 0) > 0:
            return []

        indicators = self.get_indicators(bar.symbol)
        signals: list[WatchSignal] = []

        for rule in self._watch_rules:
            try:
                if evaluate_watch_condition(rule, indicators):
                    context = build_watch_context(rule, indicators)
                    # Tag with rule index so on_watch_quote knows which rule triggered
                    context["_rule"] = rule
                    signals.append(WatchSignal(
                        symbol=bar.symbol,
                        reason=rule.get("reason", "watch rule triggered"),
                        ttl_bars=int(rule.get("ttl_bars", 5)),
                        context=context,
                    ))
            except Exception as e:
                logger.debug(f"Watch rule eval error for {self.name}: {e}")

        return signals

    def on_watch_quote(
        self,
        symbol: str,
        bid: float,
        ask: float,
        timestamp,
        context: dict,
    ) -> Optional[TradeSignal]:
        """Evaluate LLM-generated entry condition at quote time.

        Checks the rule's entry_when against mid_price and frozen context.
        Returns a buy signal if entry condition is met.
        """
        rule = context.get("_rule")
        if not rule:
            return None

        mid = (bid + ask) / 2.0
        try:
            if evaluate_entry_condition(rule, mid, context):
                qty = self.compute_quantity(mid)
                if qty > 0:
                    return TradeSignal(symbol=symbol, side="buy", quantity=qty)
        except Exception as e:
            logger.debug(f"Watch entry eval error for {self.name}: {e}")

        return None

    def on_quote(self, symbol: str, bid: float, ask: float, timestamp) -> Optional[TradeSignal]:
        """Process a real-time quote for exit decisions only.

        Called at quote frequency (per-second) for symbols the model holds.
        Default implementation checks stop-loss and take-profit against the
        model's actual entry price.

        Strategies can override for custom exit logic. Must only return sell
        signals -- quotes are not used for entries.

        Returns a TradeSignal (sell) or None.
        """
        qty = self._positions.get(symbol, 0)
        if qty <= 0:
            return None

        mid = (bid + ask) / 2.0
        entry_price = self._entry_prices.get(symbol)
        if not entry_price or entry_price <= 0:
            return None

        pct_change = (mid - entry_price) / entry_price * 100.0

        # Stop-loss: exit if price dropped below threshold
        if self.stop_loss_pct and pct_change <= -self.stop_loss_pct:
            return TradeSignal(symbol=symbol, side="sell", quantity=qty)

        # Take-profit: exit if price rose above threshold
        if self.take_profit_pct and pct_change >= self.take_profit_pct:
            return TradeSignal(symbol=symbol, side="sell", quantity=qty)

        return None

    def check_liquidation(self, bar: BarData) -> Optional[TradeSignal]:
        """If session is ending, manage position wind-down.

        Strategies should call this at the TOP of on_bar(). If it returns
        a signal, return it immediately — winding down takes priority.

        Two phases:
          NO_BUY_WINDOW (10 min): block new entries, let existing positions ride.
          LIQUIDATION_WINDOW (3 min): force-sell everything.
        """
        if bar.minutes_remaining is None:
            return None

        # Phase 2: force liquidation
        if bar.minutes_remaining <= self.LIQUIDATION_WINDOW:
            qty = self._positions.get(bar.symbol, 0)
            if qty > 0:
                return TradeSignal(
                    symbol=bar.symbol, side="sell", quantity=qty
                )
            return TradeSignal(symbol="__SKIP__", side="sell", quantity=0)

        # Phase 1: no new buys, but hold existing positions
        if bar.minutes_remaining <= self.NO_BUY_WINDOW:
            if self._positions.get(bar.symbol, 0) == 0:
                return TradeSignal(symbol="__SKIP__", side="sell", quantity=0)

        return None

    def record_bar(self, bar: BarData) -> None:
        """Store a bar in the history buffer for indicator computation.

        Synthetic bars (from quote aggregation) are skipped to prevent
        mid-price OHLC from corrupting indicator series (MA, RSI, etc.).
        """
        if bar.synthetic:
            return
        if bar.symbol not in self._bar_history:
            self._bar_history[bar.symbol] = []
        self._bar_history[bar.symbol].append(bar)

    def get_history(self, symbol: str, lookback: int = 0) -> list[BarData]:
        """Get bar history for a symbol. If lookback=0, return all."""
        history = self._bar_history.get(symbol, [])
        if lookback > 0:
            return history[-lookback:]
        return history

    def get_close_series(self, symbol: str, lookback: int = 0) -> pd.Series:
        """Get a pandas Series of close prices for indicator computation."""
        bars = self.get_history(symbol, lookback)
        if not bars:
            return pd.Series(dtype=float)
        return pd.Series(
            [b.close for b in bars],
            index=[b.timestamp for b in bars],
            dtype=float,
        )

    def adapt(self, recent_signals: list, recent_fills: list, realized_pnl: float) -> None:
        """Adapt strategy parameters based on recent intra-session performance.

        Called every 15 bars by the arena. Subclasses override to implement
        strategy-specific adaptation logic.

        Args:
            recent_signals: Last 15 bars' TradeSignal objects from this strategy
            recent_fills: Fill records (dicts with symbol, side, price, qty, pnl)
            realized_pnl: Total realized P&L in the recent window
        """
        pass  # Base class does nothing; subclasses override

    def reset(self) -> None:
        """Clear internal state for a new session."""
        self._bar_history.clear()
        self._indicators.clear()

    @classmethod
    def create(cls, name: str, params: Optional[dict] = None) -> "Strategy":
        """Factory method to create an instance with given params."""
        return cls(name=name, params=params)
